DROP TABLE noticia;

CREATE TABLE noticia (
idnoticia NUMBER(4)
    GENERATED ALWAYS AS IDENTITY
    PRIMARY KEY,
titulo VARCHAR2(200) NOT NULL,
texto VARCHAR2(4000) NOT NULL,
embedding VECTOR(384, FLOAT32)
);